---
title: "Blog Post 5"
subtitle: "Descriptions of Combined Datasets"
author: "All"
date: "2024-11-09"
date-modified: "2024-11-11"
draft: FALSE
---

We looked into various datasets that could be joined with ours, allowing a more in-depth analysis. Some of our ideas included joining datasets concerning [COVID-19](https://covid.cdc.gov/covid-data-tracker/#datatracker-home), [healthcare accessibility](https://data.hrsa.gov/data/download), [unemployment rates](https://www.bls.gov/data/#unemployment), and [weather](https://www.ncei.noaa.gov/cdo-web/datasets), all joined on either date or region. The COVID-19 dataset could account for any anomalies within our data during the pandemic’s peak, specifically recognizing changes in unemployment status and income, which may have impacted mental health. Healthcare accessibility could influence mental health, as proximity to care facilities affects the frequency of seeing medical providers. Unemployment rates by region could illustrate which places have the highest and lowest unemployment rates, and from there, we could compare which groups of people are most likely to reside in certain regions and whether their demographics impact or are impacted by other variables. Lastly, weather data could find correlations between time of year and poor mental health, potentially showing the effects of seasonal depression. By accounting for these outside variables (the COVID-19 pandemic, accessibility to healthcare facilities, unemployment status by location, and seasonal depression), we could train our model better to recognize these influences.

We ultimately chose to assess [healthcare accessibility data](https://data.hrsa.gov/DataDownload/AHRF/AHRF_SN_User%20Tech.zip), specifically the 2022-2023 State and National Level Data. One challenge with this dataset is that it has 6000 variables, but we have selected to examine specific access to providers, like social workers, primary care, psychologists, child psychiatrists, and a few others. We are merging this data on “state” to determine how healthcare accessibility varies by region and impacts mental health. We have not yet finished combining the dataset, so we do not have any preliminary analyses. Our next step is to clean the data, and from there, we can determine any initial findings.

```{r}
#| echo: false
#| include: true
library(tidyverse)

care_data_sum <- read_rds("dataset/care_data_sum.rds") |>
  mutate(psychol_21 = psychol_21 / popn_pums_21,
         socwk_21 = socwk_21 / popn_pums_21,
         conslrs_21 = conslrs_21 / popn_pums_21) |>
  pivot_longer(cols = c(psychol_21, socwk_21, conslrs_21),
               names_to = "profession",
               values_to = "value")

ggplot(care_data_sum, aes(x = value)) +
  geom_histogram(bins = 30, fill = "skyblue", color = "black") +
  facet_wrap(~profession, scales = "free_x") +
  labs(title = "Distribution of Mental Health Professionals per State",
       x = "Proportion of Profession per State",
       y = "Count") +
  theme_minimal()

```
Above are a few histograms that outline the distribution of the proportion of # of each type of specialist per person. The distributions seem to be very similar, with high counts near the left side of the range, and a right-skewed shape. This shows us that many of the proportions of specialists in each state does not seem to vary much, however there are some states with proportions of specialists that are much higher than others. We will continue to analyze this data to see if there are connections that we can create between healthcare accessibility and the other mental health statistics.
